### ISSUE TITLE
Autoban bans players on changing maps

### ISSUE THREAD

**Issue by yarik2720** [caxanga334/cvreduxmodified#19] opened 2019-11-04 11:16 UTC
**Describe the bug**
If voting for mute/kick or anything else about what to do with player were started before some seconds before map change, after map changed plugin thinks that player evade voting and autobans him.

**To Reproduce**
1. Create vote:
```
	"Mute player"
	{
		"type"			"players"
		"vote"			"1"
		"minimum"		"3"
		"cooldown"		"100"
		"ratio"			"0.5"
		"command"		"sm_silence #{TARGET_ID} 30 Muted by voting"
		"start_notify"	"{olive}[SM] {default}{VOTER_NAME} started a vote to mute {red}{TARGET_NAME}{default}."
		"call_notify"	"{olive}[SM] {default}Vote cast for {yes|no}."
		"pass_notify"	"{olive}[SM] {default}Vote passed."
		"fail_notify"	"{olive}[SM] {default}Vote failed. Received: {VOTE_AMOUNT} Required: {VOTE_REQUIRED}"
		"chattrigger"	"votemute"
	}
```
2. Start vote before map change.
3. Voting does not have time to complete before the change of map.

**Expected behavior**
Vote should be closed on map change, player shouldn't be banned for evasion.

**Game Server**
* Sourcemod version: 1.9.0.6281
* Metamod version: 1.10.7
* Custom Votes plugin version: 1.16.3U
* Game: Synergy (appid 17520)

**Comment by caxanga334** [comment] 2019-11-04 22:01
Duplicate of #7

**Closed by caxanga334** 2019-11-04 22:01 UTC

**Comment by caxanga334** [comment] 2019-11-05 17:31
Synergy doesn't fire any events when the map ends. The auto ban system is incompatible with Synergy.
